name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  test:
    uses: ./.github/workflows/test.yaml

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - run: actions/checkout@v4

      - uses: actions/download-artifact@v8
        with:
          name: worshipmate-build

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/deploy-pages@v5
        id: deployment
